"""Add voucher fields to Order model

Revision ID: 12ac08d3eceb
Revises: 4cebd07fb51f
Create Date: 2026-03-02 17:09:10.052248

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '12ac08d3eceb'
down_revision = '4cebd07fb51f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('voucher_code', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('voucher_discount', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_column('voucher_discount')
        batch_op.drop_column('voucher_code')

    # ### end Alembic commands ###
