"""Initial Migration UUIDv7

Revision ID: 186322db34ff
Revises: 
Create Date: 2026-02-04 12:54:04.645751

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '186322db34ff'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    
    # 1. Users
    op.create_table('users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('profile_pic_url', sa.String(length=255), nullable=True),
    sa.Column('password_hash', sa.String(length=255), nullable=True),
    sa.Column('is_verified', sa.Boolean(), nullable=True),
    sa.Column('otp_code', sa.String(length=6), nullable=True),
    sa.Column('otp_expires_at', sa.DateTime(), nullable=True),
    sa.Column('otp_last_sent_at', sa.DateTime(), nullable=True),
    sa.Column('otp_resend_count', sa.Integer(), nullable=True),
    sa.Column('points_balance', sa.Float(), nullable=True),
    sa.Column('points_lifetime', sa.Float(), nullable=True),
    sa.Column('current_points', sa.Float(), nullable=True),
    sa.Column('total_streak', sa.Integer(), nullable=True),
    sa.Column('last_check_in_date', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('referral_code', sa.String(length=20), nullable=True),
    sa.Column('referred_by_id', sa.String(length=36), nullable=True),
    sa.ForeignKeyConstraint(['referred_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('phone'),
    sa.UniqueConstraint('username')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_referral_code'), ['referral_code'], unique=True)

    # 2. Merchants (Removed Rewards FKs initially)
    op.create_table('merchants',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('company_reg_no', sa.String(length=50), nullable=True),
    sa.Column('referral_referrer_reward_id', sa.String(length=36), nullable=True),
    sa.Column('referral_referee_reward_id', sa.String(length=36), nullable=True),
    sa.Column('referral_referrer_points', sa.Integer(), nullable=True),
    sa.Column('referral_referee_points', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    # DEFERRED FKs: referral_referrer_reward_id, referral_referee_reward_id
    sa.PrimaryKeyConstraint('id')
    )

    # 3. Branches
    op.create_table('branches',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('merchant_id', sa.String(length=36), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('location', sa.String(length=200), nullable=True),
    sa.Column('is_main', sa.Boolean(), nullable=True),
    sa.Column('logo_url', sa.String(length=255), nullable=True),
    sa.Column('profile_pic_url', sa.String(length=255), nullable=True),
    sa.Column('points_multiplier', sa.Float(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['merchant_id'], ['merchants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )

    # 4. Rewards
    op.create_table('rewards',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('merchant_id', sa.String(length=36), nullable=False),
    sa.Column('branch_id', sa.String(length=36), nullable=True),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('image_url', sa.String(length=500), nullable=True),
    sa.Column('category', sa.String(length=50), nullable=True),
    sa.Column('is_custom', sa.Boolean(), nullable=True),
    sa.Column('reward_type', sa.String(length=50), nullable=True),
    sa.Column('target_scope', sa.String(length=50), nullable=True),
    sa.Column('target_id', sa.String(length=36), nullable=True),
    sa.Column('discount_value', sa.Float(), nullable=True),
    sa.Column('points_cost', sa.Integer(), nullable=False),
    sa.Column('min_rank_required', sa.String(length=20), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('stock_quantity', sa.Integer(), nullable=True),
    sa.Column('available_stock', sa.Integer(), nullable=True),
    sa.Column('validity_days', sa.Integer(), nullable=True),
    sa.Column('redemption_limit_per_user', sa.Integer(), nullable=True),
    sa.Column('terms_and_conditions', sa.Text(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], ),
    sa.ForeignKeyConstraint(['merchant_id'], ['merchants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )

    # 5. Lucky Draws
    op.create_table('lucky_draws',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('merchant_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('image_url', sa.String(length=500), nullable=True),
    sa.Column('points_cost', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_day7_draw', sa.Boolean(), nullable=False),
    sa.Column('max_daily_spins_per_user', sa.Integer(), nullable=True),
    sa.Column('total_available_spins', sa.Integer(), nullable=True),
    sa.Column('remaining_spins', sa.Integer(), nullable=True),
    sa.Column('start_date', sa.DateTime(), nullable=True),
    sa.Column('end_date', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['merchant_id'], ['merchants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )

    # 6. Lucky Draw Prizes
    op.create_table('lucky_draw_prizes',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('lucky_draw_id', sa.String(length=36), nullable=False),
    sa.Column('prize_type', sa.Enum('points', 'reward', 'voucher', name='prize_type_enum'), nullable=False),
    sa.Column('points_amount', sa.Integer(), nullable=True),
    sa.Column('reward_id', sa.String(length=36), nullable=True),
    sa.Column('voucher_discount_percent', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('voucher_discount_amount', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('voucher_description', sa.String(length=200), nullable=True),
    sa.Column('voucher_max_usage', sa.Integer(), nullable=True),
    sa.Column('voucher_expiry_days', sa.Integer(), nullable=True),
    sa.Column('probability_weight', sa.Integer(), nullable=False),
    sa.Column('stock_quantity', sa.Integer(), nullable=True),
    sa.Column('stock_remaining', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('display_order', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['lucky_draw_id'], ['lucky_draws.id'], ),
    sa.ForeignKeyConstraint(['reward_id'], ['rewards.id'], ),
    sa.PrimaryKeyConstraint('id')
    )

    # 7. User Rewards (Removed Lucky Draw History FK initially)
    op.create_table('user_rewards',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('reward_id', sa.String(length=36), nullable=False),
    sa.Column('merchant_id', sa.String(length=36), nullable=True),
    sa.Column('points_spent', sa.Integer(), nullable=False),
    sa.Column('redemption_code', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('redeemed_at', sa.DateTime(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('used_at', sa.DateTime(), nullable=True),
    sa.Column('used_by_branch_id', sa.String(length=36), nullable=True),
    sa.Column('source_type', sa.Enum('direct_redeem', 'lucky_draw', 'promotion', name='reward_source_enum'), nullable=False),
    sa.Column('lucky_draw_history_id', sa.String(length=36), nullable=True),
    # DEFERRED FK: lucky_draw_history_id
    sa.ForeignKeyConstraint(['merchant_id'], ['merchants.id'], ),
    sa.ForeignKeyConstraint(['reward_id'], ['rewards.id'], ),
    sa.ForeignKeyConstraint(['used_by_branch_id'], ['branches.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('redemption_code')
    )

    # 8. Lucky Draw History
    op.create_table('lucky_draw_history',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('lucky_draw_id', sa.String(length=36), nullable=False),
    sa.Column('prize_won_id', sa.String(length=36), nullable=False),
    sa.Column('points_spent', sa.Integer(), nullable=False),
    sa.Column('spin_type', sa.Enum('day7_checkin', 'points_redemption', name='spin_type_enum'), nullable=False),
    sa.Column('prize_type', sa.String(length=20), nullable=False),
    sa.Column('prize_name', sa.String(length=100), nullable=False),
    sa.Column('prize_value_json', sa.Text(), nullable=True),
    sa.Column('voucher_code', sa.String(length=50), nullable=True),
    sa.Column('user_reward_id', sa.String(length=36), nullable=True),
    sa.Column('voucher_expiry_date', sa.DateTime(), nullable=True),
    sa.Column('is_claimed', sa.Boolean(), nullable=False),
    sa.Column('claimed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['lucky_draw_id'], ['lucky_draws.id'], ),
    sa.ForeignKeyConstraint(['prize_won_id'], ['lucky_draw_prizes.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user_reward_id'], ['user_rewards.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('voucher_code')
    )

    # 9. Daily Check Ins
    op.create_table('daily_check_ins',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('check_in_date', sa.Date(), nullable=False),
    sa.Column('streak_day_count', sa.Integer(), nullable=True),
    sa.Column('points_earned', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )

    # 10. Home Banners
    op.create_table('home_banners',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('merchant_id', sa.String(length=36), nullable=False),
    sa.Column('image_url', sa.String(length=500), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['merchant_id'], ['merchants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )

    # 11. Menu Categories
    op.create_table('menu_categories',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('branch_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=True),
    sa.Column('image_url', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], ),
    sa.PrimaryKeyConstraint('id')
    )

    # 12. Product Option Groups
    op.create_table('product_option_groups',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('branch_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('min_selection', sa.Integer(), nullable=True),
    sa.Column('max_selection', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], ),
    sa.PrimaryKeyConstraint('id')
    )

    # 13. Products
    op.create_table('products',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('branch_id', sa.String(length=36), nullable=False),
    sa.Column('category_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('image_url', sa.String(length=500), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_recommended', sa.Boolean(), nullable=True),
    sa.Column('is_new', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], ),
    sa.ForeignKeyConstraint(['category_id'], ['menu_categories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )

    # 14. Product Options
    op.create_table('product_options',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('group_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('price_adjustment', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['group_id'], ['product_option_groups.id'], ),
    sa.PrimaryKeyConstraint('id')
    )

    # 15. Transactions
    op.create_table('transactions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('branch_id', sa.String(length=36), nullable=False),
    sa.Column('member_id', sa.String(length=36), nullable=False),
    sa.Column('amount_spent', sa.Float(), nullable=False),
    sa.Column('points_earned', sa.Float(), nullable=False),
    sa.Column('transaction_type', sa.String(length=50), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], ),
    sa.ForeignKeyConstraint(['member_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )

    # 16. User Vouchers
    op.create_table('user_vouchers',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('reward_id', sa.String(length=36), nullable=False),
    sa.Column('unique_code', sa.String(length=50), nullable=False),
    sa.Column('is_used', sa.Boolean(), nullable=True),
    sa.Column('used_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['reward_id'], ['rewards.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('unique_code')
    )

    # 17. Collections
    op.create_table('collections',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('merchant_id', sa.String(length=36), nullable=False),
    sa.Column('branch_id', sa.String(length=36), nullable=True),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], ),
    sa.ForeignKeyConstraint(['merchant_id'], ['merchants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )

    # 18. Collection Items
    op.create_table('collection_items',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('collection_id', sa.String(length=36), nullable=False),
    sa.Column('product_id', sa.String(length=36), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['collection_id'], ['collections.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )

    # 19. Home Top Picks
    op.create_table('home_top_picks',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('merchant_id', sa.String(length=36), nullable=False),
    sa.Column('product_id', sa.String(length=36), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['merchant_id'], ['merchants.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )

    # 20. Product Options Association
    op.create_table('product_options_association',
    sa.Column('product_id', sa.String(length=36), nullable=False),
    sa.Column('option_group_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['option_group_id'], ['product_option_groups.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('product_id', 'option_group_id')
    )

    # === POST-CREATION FOREIGN KEYS for Circular Dependencies ===
    
    # Merchants -> Rewards
    op.create_foreign_key(
        'fk_merchants_referrer_reward_id', 'merchants', 'rewards',
        ['referral_referrer_reward_id'], ['id']
    )
    op.create_foreign_key(
        'fk_merchants_referee_reward_id', 'merchants', 'rewards',
        ['referral_referee_reward_id'], ['id']
    )

    # User Rewards -> Lucky Draw History
    op.create_foreign_key(
        'fk_user_rewards_lucky_draw_history_id', 'user_rewards', 'lucky_draw_history',
        ['lucky_draw_history_id'], ['id']
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('product_options_association')
    op.drop_table('home_top_picks')
    op.drop_table('collection_items')
    op.drop_table('collections')
    op.drop_table('user_vouchers')
    op.drop_table('transactions')
    op.drop_table('product_options')
    op.drop_table('products')
    op.drop_table('product_option_groups')
    op.drop_table('menu_categories')
    op.drop_table('home_banners')
    op.drop_table('daily_check_ins')
    op.drop_table('lucky_draw_history')
    op.drop_table('user_rewards')
    op.drop_table('lucky_draw_prizes')
    op.drop_table('lucky_draws')
    op.drop_table('rewards')
    op.drop_table('branches')
    op.drop_table('merchants')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_referral_code'))

    op.drop_table('users')
    # ### end Alembic commands ###
