"""support option sharing for product

Revision ID: 1b2ce62a6765
Revises: c0e91522e70f
Create Date: 2025-12-18 15:13:19.257106

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1b2ce62a6765'
down_revision = 'c0e91522e70f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product_options_association',
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('option_group_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['option_group_id'], ['product_option_groups.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('product_id', 'option_group_id')
    )
    with op.batch_alter_table('product_option_groups', schema=None) as batch_op:
        batch_op.add_column(sa.Column('branch_id', sa.Integer(), nullable=False))
        batch_op.drop_constraint(batch_op.f('product_option_groups_product_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'branches', ['branch_id'], ['id'])
        batch_op.drop_column('product_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product_option_groups', schema=None) as batch_op:
        batch_op.add_column(sa.Column('product_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('product_option_groups_product_id_fkey'), 'products', ['product_id'], ['id'])
        batch_op.drop_column('branch_id')

    op.drop_table('product_options_association')
    # ### end Alembic commands ###
