"""add in referral program

Revision ID: 1f537e67a6f4
Revises: d193ba63eb00
Create Date: 2025-12-29 11:21:31.677588

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1f537e67a6f4'
down_revision = 'd193ba63eb00'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('merchants', schema=None) as batch_op:
        batch_op.add_column(sa.Column('referral_referrer_reward_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('referral_referee_reward_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'rewards', ['referral_referrer_reward_id'], ['id'])
        batch_op.create_foreign_key(None, 'rewards', ['referral_referee_reward_id'], ['id'])

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('referral_code', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('referred_by_id', sa.Integer(), nullable=True))
        batch_op.alter_column('phone',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
        batch_op.create_index(batch_op.f('ix_users_referral_code'), ['referral_code'], unique=True)
        batch_op.create_foreign_key(None, 'users', ['referred_by_id'], ['id'])

    # --- Data Backfill for Existing Users ---
    try:
        connection = op.get_bind()
        # Use SA Text for raw SQL execution
        import random
        import string
        
        # Helper to generate code
        def generate_unique_code():
            chars = string.ascii_uppercase + string.digits
            return ''.join(random.choice(chars) for _ in range(6))

        # Fetch all user IDs
        users_result = connection.execute(sa.text("SELECT id FROM users")).fetchall()
        
        for row in users_result:
            # row might be object or tuple depending on driver
            user_id = row[0]
            code = generate_unique_code()
            
            # Update user with generated code
            connection.execute(
                sa.text("UPDATE users SET referral_code = :code WHERE id = :id"),
                {"code": code, "id": user_id}
            )
            
    except Exception as e:
        print(f"Warning: Failed to backfill referral codes: {e}")
        # We don't block migration, but log warning. 
        # The app's lazy-generation logic will handle any we missed.

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_users_referral_code'))
        batch_op.alter_column('phone',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
        batch_op.drop_column('referred_by_id')
        batch_op.drop_column('referral_code')

    with op.batch_alter_table('merchants', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('referral_referee_reward_id')
        batch_op.drop_column('referral_referrer_reward_id')

    # ### end Alembic commands ###
