"""add in complete rewards table

Revision ID: 52efced11674
Revises: dbdceba70e00
Create Date: 2025-12-26 11:48:20.177621

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '52efced11674'
down_revision = 'dbdceba70e00'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rewards', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_custom', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('reward_type', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('target_scope', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('target_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('discount_value', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rewards', schema=None) as batch_op:
        batch_op.drop_column('discount_value')
        batch_op.drop_column('target_id')
        batch_op.drop_column('target_scope')
        batch_op.drop_column('reward_type')
        batch_op.drop_column('is_custom')

    # ### end Alembic commands ###
