"""add is_new and recommended to product

Revision ID: 852db1f78496
Revises: 1b2ce62a6765
Create Date: 2025-12-18 17:21:22.066969

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '852db1f78496'
down_revision = '1b2ce62a6765'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_new', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_column('is_new')

    # ### end Alembic commands ###
