"""add transaction_type

Revision ID: 89606ca4ba54
Revises: d04ed5aae9d2
Create Date: 2026-01-04 20:25:20.253181

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '89606ca4ba54'
down_revision = 'd04ed5aae9d2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('transaction_type', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.drop_column('transaction_type')

    # ### end Alembic commands ###
