"""Refactor Merchant and Branch auth

Revision ID: 8ec105a3ae82
Revises: bcef8501e541
Create Date: 2025-12-18 11:55:20.660066

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8ec105a3ae82'
down_revision = 'bcef8501e541'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('branches', schema=None) as batch_op:
        batch_op.add_column(sa.Column('username', sa.String(length=80), nullable=False))
        batch_op.add_column(sa.Column('password_hash', sa.String(length=255), nullable=False))
        batch_op.add_column(sa.Column('is_main', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('logo_url', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('profile_pic_url', sa.String(length=255), nullable=True))
        batch_op.create_unique_constraint(None, ['username'])

    with op.batch_alter_table('merchants', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('merchants_email_key'), type_='unique')
        batch_op.drop_column('password_hash')
        batch_op.drop_column('email')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('merchants', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email', sa.VARCHAR(length=120), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('password_hash', sa.VARCHAR(length=128), autoincrement=False, nullable=False))
        batch_op.create_unique_constraint(batch_op.f('merchants_email_key'), ['email'], postgresql_nulls_not_distinct=False)

    with op.batch_alter_table('branches', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('profile_pic_url')
        batch_op.drop_column('logo_url')
        batch_op.drop_column('is_main')
        batch_op.drop_column('password_hash')
        batch_op.drop_column('username')

    # ### end Alembic commands ###
