"""add points multiplier to branches

Revision ID: 924c4050ab67
Revises: afdf9fbf876b
Create Date: 2025-12-20 01:23:39.674057

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '924c4050ab67'
down_revision = 'afdf9fbf876b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('branches', schema=None) as batch_op:
        batch_op.add_column(sa.Column('points_multiplier', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('branches', schema=None) as batch_op:
        batch_op.drop_column('points_multiplier')

    # ### end Alembic commands ###
