"""Add email and OTP to User, remove role

Revision ID: 98e6072839cd
Revises: aeb7b2d63bda
Create Date: 2025-12-15 18:31:55.506519

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '98e6072839cd'
down_revision = 'aeb7b2d63bda'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email', sa.String(length=120), nullable=False))
        batch_op.add_column(sa.Column('is_verified', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('otp_code', sa.String(length=6), nullable=True))
        batch_op.add_column(sa.Column('otp_expires_at', sa.DateTime(), nullable=True))
        batch_op.create_unique_constraint(None, ['email'])
        batch_op.drop_column('role')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('role', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('otp_expires_at')
        batch_op.drop_column('otp_code')
        batch_op.drop_column('is_verified')
        batch_op.drop_column('email')

    # ### end Alembic commands ###
