"""Add gamification fields to User

Revision ID: bcef8501e541
Revises: 8bb27e59f67b
Create Date: 2025-12-17 22:23:43.562282

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bcef8501e541'
down_revision = '8bb27e59f67b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('total_streak', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('last_check_in_date', sa.Date(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('last_check_in_date')
        batch_op.drop_column('total_streak')

    # ### end Alembic commands ###
