"""point rewards referral

Revision ID: d04ed5aae9d2
Revises: 1f537e67a6f4
Create Date: 2026-01-04 19:15:44.411739

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd04ed5aae9d2'
down_revision = '1f537e67a6f4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('merchants', schema=None) as batch_op:
        batch_op.add_column(sa.Column('referral_referrer_points', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('referral_referee_points', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('merchants', schema=None) as batch_op:
        batch_op.drop_column('referral_referee_points')
        batch_op.drop_column('referral_referrer_points')

    # ### end Alembic commands ###
