"""add_rewards_system_with_dual_points

Revision ID: d13582494301
Revises: 1039a3e0a8ac
Create Date: 2025-12-23 02:03:54.779514

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd13582494301'
down_revision = '1039a3e0a8ac'
branch_labels = None
depends_on = None


def upgrade():
    # Drop old rewards table and recreate with new schema
    # (Safe because old reward system wasn't in production use)
    op.drop_table('user_vouchers')
    op.drop_table('rewards')

    # Create new rewards table with full schema
    op.create_table('rewards',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('merchant_id', sa.Integer(), nullable=False),
        sa.Column('branch_id', sa.Integer(), nullable=True),
        sa.Column('title', sa.String(length=200), nullable=False),
        sa.Column('description', sa.Text(), nullable=True),
        sa.Column('image_url', sa.String(length=500), nullable=True),
        sa.Column('category', sa.String(length=50), nullable=True),
        sa.Column('points_cost', sa.Integer(), nullable=False),
        sa.Column('min_rank_required', sa.String(length=20), nullable=True),
        sa.Column('is_active', sa.Boolean(), nullable=True),
        sa.Column('stock_quantity', sa.Integer(), nullable=True),
        sa.Column('available_stock', sa.Integer(), nullable=True),
        sa.Column('validity_days', sa.Integer(), nullable=True),
        sa.Column('redemption_limit_per_user', sa.Integer(), nullable=True),
        sa.Column('terms_and_conditions', sa.Text(), nullable=True),
        sa.Column('sort_order', sa.Integer(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.Column('updated_at', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], ),
        sa.ForeignKeyConstraint(['merchant_id'], ['merchants.id'], ),
        sa.PrimaryKeyConstraint('id')
    )

    # Create user_rewards table
    op.create_table('user_rewards',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('user_id', sa.Integer(), nullable=False),
        sa.Column('reward_id', sa.Integer(), nullable=False),
        sa.Column('merchant_id', sa.Integer(), nullable=True),
        sa.Column('points_spent', sa.Integer(), nullable=False),
        sa.Column('redemption_code', sa.String(length=20), nullable=False),
        sa.Column('status', sa.String(length=20), nullable=True),
        sa.Column('redeemed_at', sa.DateTime(), nullable=True),
        sa.Column('expires_at', sa.DateTime(), nullable=True),
        sa.Column('used_at', sa.DateTime(), nullable=True),
        sa.Column('used_by_branch_id', sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(['merchant_id'], ['merchants.id'], ),
        sa.ForeignKeyConstraint(['reward_id'], ['rewards.id'], ),
        sa.ForeignKeyConstraint(['used_by_branch_id'], ['branches.id'], ),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('redemption_code')
    )

    # Recreate user_vouchers for backward compatibility
    op.create_table('user_vouchers',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('user_id', sa.Integer(), nullable=False),
        sa.Column('reward_id', sa.Integer(), nullable=False),
        sa.Column('unique_code', sa.String(length=50), nullable=False),
        sa.Column('is_used', sa.Boolean(), nullable=True),
        sa.Column('used_at', sa.DateTime(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(['reward_id'], ['rewards.id'], ),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('unique_code')
    )

    # Update users table with dual points system
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('points_balance', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('points_lifetime', sa.Float(), nullable=True))

    # Migrate existing points data: current_points -> both balance and lifetime
    op.execute('UPDATE users SET points_balance = current_points, points_lifetime = current_points WHERE current_points IS NOT NULL')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('points_lifetime')
        batch_op.drop_column('points_balance')

    with op.batch_alter_table('rewards', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('cost_points', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('voucher_value', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('description',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
        batch_op.drop_column('updated_at')
        batch_op.drop_column('sort_order')
        batch_op.drop_column('terms_and_conditions')
        batch_op.drop_column('redemption_limit_per_user')
        batch_op.drop_column('validity_days')
        batch_op.drop_column('available_stock')
        batch_op.drop_column('stock_quantity')
        batch_op.drop_column('min_rank_required')
        batch_op.drop_column('points_cost')
        batch_op.drop_column('category')
        batch_op.drop_column('image_url')
        batch_op.drop_column('title')
        batch_op.drop_column('branch_id')
        batch_op.drop_column('merchant_id')

    op.drop_table('user_rewards')
    # ### end Alembic commands ###
