"""add_points_earned_to_daily_check_ins

Revision ID: dbdceba70e00
Revises: d13582494301
Create Date: 2025-12-23 16:26:13.645069

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dbdceba70e00'
down_revision = 'd13582494301'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('daily_check_ins', schema=None) as batch_op:
        batch_op.add_column(sa.Column('points_earned', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('daily_check_ins', schema=None) as batch_op:
        batch_op.drop_column('points_earned')

    # ### end Alembic commands ###
